body:
  - type: dropdown
    id: version
    attributes:
      label: Minecraft Version
      description: Please select the Minecraft game version where you are experiencing this issue.
      options:
        - "1.21"
        - "1.20.4"
        - "1.20.1"
        - "1.19.4"
        - "Other (Specify in text)"
    validations:
      required: true
