body:
  - type: textarea
    id: version
    attributes:
      label: Minecraft Version
      description: Please state the Minecraft game version where you are experiencing this issue.
    validations:
      required: true
